### ISSUE TITLE
flagsReady boolean not set

### ISSUE THREAD

**Issue by lnmp4000** [Unleash/proxy-client-react#29] opened 2021-12-16 11:20 UTC
I'm running an SPA using a local instance of the unleashed proxy as detailed in the documentation, connecting to the unleashed cloud test instance.
https://app.unleash-hosted.com/demo/api/

The first time I enter my application, i.e. with a clear cache, the flags load and the `flagsReady` flag correctly is set to `true`.

However, if I refresh my SPA, the `flagsReady` flag is not set to true.
Clearing the local cache and refreshing, fixes the issue.

I can see the successful network request
![image](https://user-images.githubusercontent.com/2903591/146360852-4b1bbb79-de9f-4133-ab2b-050077577bd1.png)

But the state in the hook indicates the flags are not loaded.

![image](https://user-images.githubusercontent.com/2903591/146362535-f84e7ef7-b1a1-467b-b472-057327e5889c.png)

**Comment by FredrikOseberg** [comment] 2021-12-16 12:08
> I'm running an SPA using a local instance of the unleashed proxy as detailed in the documentation, connecting to the unleashed cloud test instance. https://app.unleash-hosted.com/demo/api/
> 
> The first time I enter my application, i.e. with a clear cache, the flags load and the `flagsReady` flag correctly is set to `true`.
> 
> However, if I refresh my SPA, the `flagsReady` flag is not set to true. Clearing the local cache and refreshing, fixes the issue.
> 
> I can see the successful network request ![image](https://user-images.githubusercontent.com/2903591/146360852-4b1bbb79-de9f-4133-ab2b-050077577bd1.png)
> 
> But the state in the hook indicates the flags are not loaded.
> 
> ![image](https://user-images.githubusercontent.com/2903591/146362535-f84e7ef7-b1a1-467b-b472-057327e5889c.png)

I'm looking into this, but so far I can't reproduce. Tried with both our demo app and a fresh CRA template app. Do you have a reproducible example?

**Comment by lnmp4000** [comment] 2021-12-16 13:25
It may have been caused by me incorrectly setting `undefined` as the `userId` in the following call.

```
    useEffect(() => {
        // context is updated with userId
        updateContext({ userId: username });
    }, [username, updateContext]);
```
I corrected that particular issue and now the flag seems to be working as expected.

**Comment by FredrikOseberg** [comment] 2021-12-16 13:36
> It may have been caused by me incorrectly setting `undefined` as the `userId` in the following call.
> 
> ```
>     useEffect(() => {
>         // context is updated with userId
>         updateContext({ userId: username });
>     }, [username, updateContext]);
> ```
> 
> I corrected that particular issue and now the flag seems to be working as expected.

Ok, thanks for the info. Closing this for now. Feel free to reopen later if you find there is an issue.

**Closed by FredrikOseberg** 2021-12-16 13:36 UTC
