### ISSUE TITLE
Duplicate Proxy Calls

### ISSUE THREAD

**Issue by melloware** [Unleash/proxy-client-react#77] opened 2022-09-22 20:25 UTC
### Describe the bug

Using latest React SDK I see the Proxy be query two times constantly.

![image](https://user-images.githubusercontent.com/4399574/191844055-2dc7c926-1be7-42b0-bc42-49dc6061c601.png)

### Steps to reproduce the bug

Just run React app with proxy and watch the F12 network traffic.

### Expected behavior

Only 1 call every 15 seconds

### Additional context

```js
const unleashInstance: IConfig = {
	url: process.env.REACT_APP_UNLEASH_SERVER!,
	clientKey: process.env.REACT_APP_UNLEASH_KEY!,
	refreshInterval: 15,
	appName: 'clm',
	environment: process.env.REACT_APP_UNLEASH_ENV!,
	disableMetrics: true
};
```

### Unleash version

Latest

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

"@unleash/proxy-client-react": "^3.3.0",

**Comment by sighphyre** [comment] 2022-09-23 08:52
Hmm, this looks odd, thanks for raising this one. I'll add this to our list of things to look into next week

**Comment by FredrikOseberg** [comment] 2022-09-23 09:44
@melloware Is this happening in development or production?

**Comment by melloware** [comment] 2022-09-23 10:27
i am in development mode right now.

**Comment by melloware** [comment] 2022-09-23 10:28
i wasn't sure if this was a problem with React SDK or the client Proxy SDK so I reported it in both.

**Comment by FredrikOseberg** [comment] 2022-09-23 11:48
> i wasn't sure if this was a problem with React SDK or the client Proxy SDK so I reported it in both.

Thanks for the clarification! I think this is not a bug with this project, but actually how hot module reloading works according to [this issue](https://github.com/gaearon/react-hot-loader/issues/930).

I will close this issue for now, feel free to re-open if you disagree.

**Closed by FredrikOseberg** 2022-09-23 11:48 UTC
Labels: bug

**Comment by melloware** [comment] 2022-09-23 22:36
What is interesting about this is it starts happening even if I load my app fresh so its not like I have done any hot reloads or anything?

Also it looks like the Hot Reload library is no longer needed as Fast Refresh is already included in Core React right?  See: https://github.com/facebook/react/issues/16604

**Comment by melloware** [comment] 2022-09-23 22:43
I actually think to be  good citizen you should be calling STOP on unmount as well like this..

```js
React.useEffect(() => {
    const shouldStartClient = startClient || !unleashClient;
    if (shouldStartClient) {
      client.current.start();
    }

    // stop unleash client on unmount
    return function cleanup() {
       client.current.stop();
    };
  }, []);
```

**Comment by FredrikOseberg** [comment] 2022-09-23 22:48
> What is interesting about this is it starts happening even if I load my app fresh so its not like I have done any hot reloads or anything?
> 
> Also it looks like the Hot Reload library is no longer needed as Fast Refresh is already included in Core React right? See: [facebook/react#16604](https://github.com/facebook/react/issues/16604)

Are you using react in strict mode? [See this issue](https://github.com/facebook/react/issues/24425)

**Comment by FredrikOseberg** [comment] 2022-09-23 22:52
> I actually think to be good citizen you should be calling STOP on unmount as well like this..
> 
> ```js
> React.useEffect(() => {
>     const shouldStartClient = startClient || !unleashClient;
>     if (shouldStartClient) {
>       client.current.start();
>     }
> 
>     // stop unleash client on unmount
>     return function cleanup() {
>        client.current.stop();
>     };
>   }, []);
> ```

Good idea. Feel free to open a separate issue or contribute a PR if you'd like. Otherwise I'll try to get to it next week.

**Comment by melloware** [comment] 2022-09-23 22:52
Yep confirmed its REact 18 Strict Mode causing the issue!!!

  So what happens is render gets called twice to make sure you are being a good citizen with your renders.    I have fixed this in other projects where they were not handling the renders correctly.

Like this one I reported in `use-between` and he fixed it: https://github.com/betula/use-between/issues/33

**Comment by melloware** [comment] 2022-09-23 22:53
OK i will submit a PR.
